"""updted models

Revision ID: 8b5f6c671cae
Revises: 
Create Date: 2024-12-21 14:22:30.772719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5f6c671cae'
down_revision: Union[str, None] = 'd981f1961256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('close_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('auth_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ip_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('discord_notification', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('layout', postgresql.ENUM('PAGE','CARD', name='layout'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='forms_pkey'),
    sa.UniqueConstraint('form_id', name='forms_form_id_key')
    )

    op.create_table('form-pages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], name='form-pages_form_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='form-pages_pkey')
    )

    op.create_table('form-submission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submission_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], name='form-submission_form_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='form-submission_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS layout cascade")
    # deleting the child tables first
    op.drop_table('form-pages')
    op.drop_table('form-submission')
    op.drop_table('forms')
    # ### end Alembic commands ###
