"""initial commit

Revision ID: d01a09d824c4
Revises: 
Create Date: 2024-12-12 22:17:58.913510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd01a09d824c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permission', postgresql.ENUM('READ', 'WRITE', 'DELETE', name='permission'), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('FEEDBACK', 'POLL', name='type'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('user_id', 'document_id', 'permission', 'type', name='unique_permission')
    )
    # ### end Alembic commands ###
